# Generated by Django 5.2 on 2025-05-07 14:26

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('fil', django.db.models.manager.Manager()),
            ],
        ),
    ]
